### ISSUE TITLE
Why is gh-pages branch in this repo?

### ISSUE THREAD

**Issue by jarifibrahim** [tapasweni-pathak/pyQTopic#10]
The gh-pages branch is already in projects repository. Kindly delete it from this repository.

**Comment by jarifibrahim** [comment]
https://testpypi.python.org/pypi/qtopic/0.1.0 has older version of the module. Update it.

**Comment by tapaswenipathak** [comment]
@jarifibrahim I need to [publish](http://tapasweni-pathak.github.io/pyQTopic/) the information as a web page, that's why gh-pages has been added.

Please don't use testpypi version, use the live server, that has the updated package.

I am closing this issue, reopen if needed.
