### ISSUE TITLE
Followers count doesn't work for all topic

### ISSUE THREAD

**Issue by jarifibrahim** [tapasweni-pathak/pyQTopic#12]
get_followers_count() method works for topic = 'Computer-Programming' but doesn't work for 'India', 'Small-Businesses', 'Retail'. For these topics the `<span class='count'>` doesn't appear unless you're logged in to quora. So the html_doc downloaded by the methods does not have followers count.

**Comment by ritece** [comment]
I tried a few topics like, "Nasa", "Computer-Programming" etc. but it does not work.

**Comment by vivekaltruist** [comment]
This can be fixed by following function:

`    def get_follower_count(topic):
        url = "https://www.quora.com/" + topic
        html_doc = urllib2.urlopen(url)
        soup = BeautifulSoup(html_doc.read())
        #print soup.find_all('span')
        raw_data = str(soup.find_all('a', class_="TopicFollowersStatsRow StatsRow"))
        soup = BeautifulSoup(raw_data)
        followers = soup.find_all('strong')[0].get_text()
        dict = {
            'topic': topic,
            'followers': followers,
        }
        return dict
`

**Comment by vivekaltruist** [comment]
This issue is fixed by following definition:
`
    def get_follower_count(topic):
        url = "https://www.quora.com/" + topic
        html_doc = urllib2.urlopen(url)
        soup = BeautifulSoup(html_doc.read())
        #print soup.find_all('span')
        raw_data = str(soup.find_all('a', class_="TopicFollowersStatsRow StatsRow"))
        soup = BeautifulSoup(raw_data)
        followers = soup.find_all('strong')[0].get_text()
        dict = {
            'topic': topic,
            'followers': followers,
        }
        return dict
`

**Comment by vivekaltruist** [comment]
Issue fixed by following definition:

```
def get_follower_count(topic):
    url = "https://www.quora.com/" + topic
    html_doc = urllib2.urlopen(url)
    soup = BeautifulSoup(html_doc.read())
    #print soup.find_all('span')
    raw_data = str(soup.find_all('a', class_="TopicFollowersStatsRow StatsRow"))
    soup = BeautifulSoup(raw_data)
    followers = soup.find_all('strong')[0].get_text()
    dict = {
        'topic': topic,
        'followers': followers,
    }
    return dict
```

**Comment by nishikeshKardak** [comment]
Issue fixed by following code
```
from bs4 import BeautifulSoup
import urllib3

def get_follower_count(topic):
    http = urllib3.PoolManager()
    url = "https://www.quora.com/topic/" + topic
    res = http.request('GET', url)
    sun = (res.data)
    soup = BeautifulSoup(sun, "html.parser")
    des = soup.find("a", {"class" : "TopicFollowersStatsRow"})
    follower_count = (des.strong).string
    dict = {
        'topic': topic,
        'followers': follower_count
    }
    return(dict)
```

**Comment by tapaswenipathak** [comment]
@vivekaltruist @nishikeshKardak Feel free create a PR, thanks!
